In [2]:
import scipy.stats as stats
import pandas as pd
import scipy.stats as stats
import numpy as np

In [1]:
import pandas as pd
from IPython.display import display, HTML

# Leer el archivo CSV
data = pd.read_csv('preparacion de datos\\registro de nacimientos\\minsalud_registro_nacidos.csv')


# Lista de columnas a eliminar
columnas_a_eliminar = ['nacidos_vivos', 'nacidos_vivos_atendidos_por_personal_de_salud']

# Eliminar las columnas
data = data.drop(columnas_a_eliminar, axis=1)

# Manejar valores no finitos antes de la conversiÃ³n
columnas_enteras = ['nacidos_muertos', 'nacidos_muertos_atendidos_por_partera']
data[columnas_enteras] = data[columnas_enteras].fillna(0).astype(int)

# Supongamos que 'columna1' y 'columna2' son tus columnas numÃ©ricas
columnas_numericas = ['nacidos_muertos', 'nacidos_muertos_atendidos_por_partera', 'total_general']

# Crear un estilo para centrar todas las celdas
styles = [
    {'selector': 'td', 'props': [('text-align', 'center')]},
    {'selector': 'th', 'props': [('text-align', 'center')]}
]

# Aplicar estilo general para centrar toda la tabla
styled_data = data.style.set_table_styles(styles)

# Mostrar la tabla estilizada
display(styled_data)

In [2]:
ruta_guardar_csv = 'D:\\Proyecto diplomado - Leonel Lizarraga\\datasets actualizados\\registro de nacimientos\\registro_de_nacimientos.csv'  
data.to_csv(ruta_guardar_csv, index=False)