In [1]:
import pandas as pd

df = pd.read_csv('preparacion de datos\Hoja 3_Resumen.csv', delimiter=';')
df

   Departamento  Año de Gestion  Total Establecimientos De Salud
0          BENI            2015                              239
1          BENI            2014                              231
2          BENI            2013                              220
3          BENI            2012                              219
4          BENI            2011                              210
..          ...             ...                              ...
58       TARIJA            2013                              252
59       TARIJA            2012                              243
60       TARIJA            2011                              231
61       TARIJA            2010                              221
62       TARIJA            2009                              213

[63 rows x 3 columns]

In [19]:
import pandas as pd
import numpy as np

# Supongamos que tu DataFrame se llama 'df'
# Asegúrate de que la columna 'Año de Gestion' sea de tipo int para que la extrapolación funcione correctamente

# Verifica y convierte el tipo de dato si es necesario
df['Año de Gestion'] = df['Año de Gestion'].astype(int)

# Crea un DataFrame para almacenar la proyección
proyeccion_df = pd.DataFrame(columns=df.columns)

# Define los años para los que deseas hacer la proyección (2016 a 2025)
years_proyeccion = range(2016, 2031)

# Itera por cada departamento y realiza la extrapolación
for departamento in df['Departamento'].unique():
    # Filtra los datos por departamento
    departamento_df = df[df['Departamento'] == departamento]
    
    # Realiza la extrapolación utilizando numpy.polyfit
    coeficientes = np.polyfit(departamento_df['Año de Gestion'], departamento_df['Total Establecimientos De Salud'], deg=1)
    
    # Genera la proyección para los años deseados
    proyeccion_valores = np.polyval(coeficientes, years_proyeccion)
    
    # Redondea los valores a números enteros
    proyeccion_valores = np.round(proyeccion_valores).astype(int)
    
    # Crea un DataFrame temporal para almacenar la proyección del departamento actual
    proyeccion_departamento_df = pd.DataFrame({
        'Departamento': [departamento] * len(years_proyeccion),
        'Año de Gestion': years_proyeccion,
        'Total Establecimientos De Salud': proyeccion_valores
    })
    
    # Concatena el DataFrame temporal al DataFrame de proyección general
    proyeccion_df = pd.concat([proyeccion_df, proyeccion_departamento_df])

# Convierte la columna 'Total Establecimientos De Salud' a tipo entero
proyeccion_df['Total Establecimientos De Salud'] = proyeccion_df['Total Establecimientos De Salud'].astype(int)

# Muestra el DataFrame de proyección
print(proyeccion_df)

   Departamento Año de Gestion  Total Establecimientos De Salud
0          BENI           2016                              248
1          BENI           2017                              257
2          BENI           2018                              265
3          BENI           2019                              273
4          BENI           2020                              282
..          ...            ...                              ...
10       TARIJA           2026                              373
11       TARIJA           2027                              383
12       TARIJA           2028                              392
13       TARIJA           2029                              402
14       TARIJA           2030                              411

[135 rows x 3 columns]

In [20]:
proyeccion_df

   Departamento Año de Gestion  Total Establecimientos De Salud
0          BENI           2016                              248
1          BENI           2017                              257
2          BENI           2018                              265
3          BENI           2019                              273
4          BENI           2020                              282
..          ...            ...                              ...
10       TARIJA           2026                              373
11       TARIJA           2027                              383
12       TARIJA           2028                              392
13       TARIJA           2029                              402
14       TARIJA           2030                              411

[135 rows x 3 columns]

In [21]:
print(proyeccion_df.dtypes)

Departamento                       object
Año de Gestion                     object
Total Establecimientos De Salud     int32
dtype: object

In [22]:
# Guarda el DataFrame de proyección en un archivo CSV
proyeccion_df.to_csv('preparacion de datos\proyeccion_establecimientos_salud.csv', index=False)